# Generated by Django 4.1.3 on 2024-07-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("LOT_Name", models.CharField(max_length=100)),
                ("lBags", models.CharField(max_length=100)),
                ("Total_Kgs", models.CharField(max_length=100)),
                ("Rate_Per_Kg", models.CharField(max_length=100)),
                ("Amount_Rs", models.CharField(max_length=100)),
            ],
        ),
    ]
