# Generated by Django 4.1.3 on 2024-07-08 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_deduction"),
    ]

    operations = [
        migrations.CreateModel(
            name="total",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("totalBags", models.FloatField()),
                ("totalkgs", models.FloatField()),
                ("totalAmount", models.FloatField()),
                ("Deduction", models.FloatField()),
                ("totalnetAmount", models.FloatField()),
            ],
        ),
    ]
