# Generated by Django 4.1.3 on 2024-07-08 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="total",
            name="Deduction",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="total",
            name="totalAmount",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="total",
            name="totalBags",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="total",
            name="totalkgs",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="total",
            name="totalnetAmount",
            field=models.CharField(max_length=100),
        ),
    ]
