# Generated by Django 4.1.3 on 2024-07-28 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_remove_deduction_commission"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bill",
            name="Amount_Rs",
        ),
    ]
