# Generated by Django 4.1.3 on 2024-08-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_bill_amount_rs"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deduction",
            name="Brokerage",
        ),
    ]
