# Generated by Django 4.1.3 on 2024-08-06 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_remove_deduction_brokerage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="total",
        ),
    ]
